
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173


gfcli:
  # build:
  #   name:     "xyhelper-gpt"
  #   arch:     "linux"
  #   system:   "amd64"
  #   packSrc:  "resource"
  #   output:   "./bin"


